### ISSUE TITLE
what's going on with Firefox and the DSX website?

### ISSUE THREAD

**Issue by tiffrobo** [digital-security-exchange/exchange-new#27]
@levjoy @redaranj 
<img width="1411" alt="screen shot 2018-09-27 at 10 12 15 am" src="https://user-images.githubusercontent.com/30634981/46156350-f0e37700-c23e-11e8-92f4-be84ec2862ca.png">
<img width="1411" alt="screen shot 2018-09-27 at 10 12 22 am" src="https://user-images.githubusercontent.com/30634981/46156351-f0e37700-c23e-11e8-9af1-a81da36d9abd.png">

**Comment by abeluck** [comment]
this looks like a cache issue, and you reported it around the time i deployed the new version. Try hard refreshing with `CMD+R`

**Comment by tiffrobo** [comment]
Hmmm.. I tried the hard refresh and I'm still seeing the firefox issue. Can someone else test this, please?
To test: load the DSX website on firefox browser

**Comment by levjoy** [comment]
Works for me on Firefox mobile.

**Comment by redaranj** [comment]
It's working fine for me on desktop Firefox. Is it possible that that's a super old version? It hasn't looked like that in a while - the current version is 62.

**Comment by tiffrobo** [comment]
Well great! It may be an old version. If it's working for you all, I'm going to close the ticket 👍
